version: '3.0'
services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres:3.4.4"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      #- ./start-tb.sh:/usr/bin/start-tb.sh
      - ./mytb-data:/data
      - ./mytb-logs:/var/log/thingsboard

